# Generated by Django 3.2.13 on 2023-03-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcoreservis',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ourcoreservis',
            name='rus_desc',
            field=models.CharField(max_length=200),
        ),
    ]
