# Generated by Django 3.2.13 on 2023-03-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230329_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcoreservis',
            name='desc',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ourcoreservis',
            name='rus_desc',
            field=models.TextField(max_length=300),
        ),
    ]
