# Generated by Django 3.2.13 on 2023-04-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230329_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='rus_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
