# Generated by Django 4.1.7 on 2023-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gallery_ourprojects_alter_base_rus_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_title', models.CharField(max_length=200)),
                ('ru_title', models.CharField(max_length=200)),
                ('uz_mini_desc', models.CharField(max_length=200)),
                ('ru_mini_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
