# Generated by Django 3.2.13 on 2023-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_about_rus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='rus_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='rus_title',
            field=models.CharField(max_length=200),
        ),
    ]
