# Generated by Django 3.2.13 on 2023-04-01 17:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230401_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='rus_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
