# Generated by Django 4.1.7 on 2023-03-29 12:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_infodev_ourcoreservis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
