# Generated by Django 3.2.13 on 2023-04-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_about_rus_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='rus_title',
            new_name='ru_title',
        ),
    ]
