# Generated by Django 3.2.13 on 2023-04-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_rus_title_gallery_ru_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='ru_title',
            new_name='rus_title',
        ),
    ]
